# Generated by Django 4.2.6 on 2023-11-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(verbose_name='порядковый номер')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('desc', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Образовательный модуль',
                'verbose_name_plural': 'Образовательные модули',
            },
        ),
    ]
